name: CI
on:
  push:
    branches:
      - main
      - r[1-9]
  pull_request:
    branches:
      - main
      - r[1-9]
jobs:
  build-and-push-slo-violation-detector:
    name: Build and push slo-violation-detector
    uses: eu-nebulous/github-actions/.github/workflows/build-and-push-container-image.yml@main
    with:
      context: slo-violation-detector
      image-name: slo-violation-detector
    secrets: inherit
